"""añadi precio en clase

Revision ID: 380d8bba8e5d
Revises: 8b7d0a2f2b1a
Create Date: 2026-05-18 12:50:10.032823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380d8bba8e5d'
down_revision: Union[str, Sequence[str], None] = '8b7d0a2f2b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('actividad_nombre_key'), 'actividad', type_='unique')
    op.create_index(op.f('ix_actividad_nombre'), 'actividad', ['nombre'], unique=True)
    op.add_column('clase', sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint(op.f('uq_persona_dni'), 'persona', type_='unique')
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=False)
    op.create_unique_constraint(op.f('uq_persona_dni'), 'persona', ['dni'], postgresql_nulls_not_distinct=False)
    op.drop_column('clase', 'precio')
    op.drop_index(op.f('ix_actividad_nombre'), table_name='actividad')
    op.create_unique_constraint(op.f('actividad_nombre_key'), 'actividad', ['nombre'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
