"""eliminacion logica de clase

Revision ID: 588fff512ca9
Revises: 1faff749ebf0
Create Date: 2026-06-16 01:07:58.425043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588fff512ca9'
down_revision: Union[str, Sequence[str], None] = '1faff749ebf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clase', sa.Column('is_eliminated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clase', 'is_eliminated')
    # ### end Alembic commands ###
