"""add_motivo_bloqueo_to_persona

Revision ID: 839a70a1bb65
Revises: 631e3c295d20
Create Date: 2026-06-14 23:09:03.482085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839a70a1bb65'
down_revision: Union[str, Sequence[str], None] = '631e3c295d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('motivo_bloqueo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'motivo_bloqueo')
    # ### end Alembic commands ###
