"""agregando confirmar turno

Revision ID: 926c4f5cbcef
Revises: b32b299a9925
Create Date: 2026-05-24 20:09:19.823998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926c4f5cbcef'
down_revision: Union[str, Sequence[str], None] = 'b32b299a9925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmacion_turno',
    sa.Column('confirmacion_turno_id', sa.Integer(), nullable=False),
    sa.Column('lista_espera_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='pendiente', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lista_espera_id'], ['lista_espera.lista_espera_id'], ),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.persona_id'], ),
    sa.PrimaryKeyConstraint('confirmacion_turno_id')
    )
    op.create_index(op.f('ix_confirmacion_turno_lista_espera_id'), 'confirmacion_turno', ['lista_espera_id'], unique=False)
    op.create_index(op.f('ix_confirmacion_turno_socio_id'), 'confirmacion_turno', ['socio_id'], unique=False)
    op.create_index(op.f('ix_confirmacion_turno_token'), 'confirmacion_turno', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmacion_turno_token'), table_name='confirmacion_turno')
    op.drop_index(op.f('ix_confirmacion_turno_socio_id'), table_name='confirmacion_turno')
    op.drop_index(op.f('ix_confirmacion_turno_lista_espera_id'), table_name='confirmacion_turno')
    op.drop_table('confirmacion_turno')
    # ### end Alembic commands ###
