"""add attendance and reservation models

Revision ID: b2368cb5427e
Revises: 7b9f7f8c1f5d
Create Date: 2026-05-13 12:14:44.388716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2368cb5427e'
down_revision: Union[str, Sequence[str], None] = '7b9f7f8c1f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad',
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('actividad_id')
    )
    op.create_index(op.f('ix_actividad_nombre'), 'actividad', ['nombre'], unique=True)
    op.create_table('cancha',
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('cancha_id')
    )
    op.create_index(op.f('ix_cancha_nombre'), 'cancha', ['nombre'], unique=True)
    op.create_table('nivel',
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('nivel_id')
    )
    op.create_index(op.f('ix_nivel_nombre'), 'nivel', ['nombre'], unique=True)
    op.create_table('profesor',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('profesor_id')
    )
    op.create_index(op.f('ix_profesor_dni'), 'profesor', ['dni'], unique=True)
    op.create_table('clase',
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.Column('fecha_clase', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cupo_total', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='activa', nullable=False),
    sa.Column('cancelada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad.actividad_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.cancha_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nivel_id'], ['nivel.nivel_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.profesor_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('clase_id')
    )
    op.create_table('abono_mensual',
    sa.Column('abono_mensual_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('abono_anterior_id', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('dia_semana', sa.String(length=30), nullable=False),
    sa.Column('descuento_aplicado_pct', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('prioridad_renovacion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fecha_limite_renovacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), server_default='activo', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abono_anterior_id'], ['abono_mensual.abono_mensual_id'], ),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad.actividad_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.persona_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('abono_mensual_id')
    )
    op.create_table('lista_espera',
    sa.Column('lista_espera_id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='pendiente', nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vence_confirmacion_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.persona_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lista_espera_id')
    )
    op.create_table('reserva',
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('abono_mensual_id', sa.Integer(), nullable=True),
    sa.Column('lista_espera_origen_id', sa.Integer(), nullable=True),
    sa.Column('tipo_reserva', sa.String(length=50), server_default='normal', nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='pendiente', nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['abono_mensual_id'], ['abono_mensual.abono_mensual_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clase_id'], ['clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lista_espera_origen_id'], ['lista_espera.lista_espera_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.persona_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_id')
    )
    op.create_table('qr_asistencia',
    sa.Column('qr_asistencia_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escaneado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), server_default='activo', nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.reserva_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qr_asistencia_id')
    )
    op.create_index(op.f('ix_qr_asistencia_token_hash'), 'qr_asistencia', ['token_hash'], unique=True)
    op.create_table('asistencia',
    sa.Column('asistencia_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('qr_asistencia_id', sa.Integer(), nullable=True),
    sa.Column('empleado_registro_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('medio_registro', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['empleado_registro_id'], ['empleado.persona_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_asistencia_id'], ['qr_asistencia.qr_asistencia_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.reserva_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asistencia_id'),
    sa.UniqueConstraint('reserva_id')
    )
    op.drop_constraint(op.f('permiso_codigo_key'), 'permiso', type_='unique')
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=True)
    op.drop_constraint(op.f('persona_email_key'), 'persona', type_='unique')
    op.drop_constraint(op.f('uq_persona_dni'), 'persona', type_='unique')
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=True)
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=True)
    op.drop_constraint(op.f('rol_nombre_key'), 'rol', type_='unique')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=False)
    op.create_unique_constraint(op.f('rol_nombre_key'), 'rol', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=False)
    op.drop_index(op.f('ix_persona_dni'), table_name='persona')
    op.create_index(op.f('ix_persona_dni'), 'persona', ['dni'], unique=False)
    op.create_unique_constraint(op.f('uq_persona_dni'), 'persona', ['dni'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('persona_email_key'), 'persona', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('permiso_codigo_key'), 'permiso', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_qr_asistencia_token_hash'), table_name='qr_asistencia')
    op.drop_table('qr_asistencia')
    op.drop_table('reserva')
    op.drop_table('lista_espera')
    op.drop_table('abono_mensual')
    op.drop_table('clase')
    op.drop_index(op.f('ix_profesor_dni'), table_name='profesor')
    op.drop_table('profesor')
    op.drop_index(op.f('ix_nivel_nombre'), table_name='nivel')
    op.drop_table('nivel')
    op.drop_index(op.f('ix_cancha_nombre'), table_name='cancha')
    op.drop_table('cancha')
    op.drop_index(op.f('ix_actividad_nombre'), table_name='actividad')
    op.drop_table('actividad')
    # ### end Alembic commands ###
