"""create profesor+clase

Revision ID: c6146a5ee162
Revises: e3a8f9f8cb79
Create Date: 2026-05-15 20:09:50.218967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6146a5ee162'
down_revision: Union[str, Sequence[str], None] = 'e3a8f9f8cb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=25), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('profesor_id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('clase',
    sa.Column('clase_id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.Enum('VOLEY', 'FUTBOL', 'PADEL', 'BASQUET', name='actividadenum'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fin', sa.Time(), nullable=False),
    sa.Column('cancha', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.Enum('PRINCIPIANTE', 'INTERMEDIO', 'AVANZADO', name='nivelenum'), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.Column('tipo_clase', sa.Enum('GRUPAL', 'PARTICULAR', name='tipoclaseenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.profesor_id'], ),
    sa.PrimaryKeyConstraint('clase_id')
    )
    op.drop_constraint(op.f('permiso_codigo_key'), 'permiso', type_='unique')
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=True)
    op.drop_constraint(op.f('persona_email_key'), 'persona', type_='unique')
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=True)
    op.drop_constraint(op.f('rol_nombre_key'), 'rol', type_='unique')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=False)
    op.create_unique_constraint(op.f('rol_nombre_key'), 'rol', ['nombre'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=False)
    op.create_unique_constraint(op.f('persona_email_key'), 'persona', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_permiso_codigo'), table_name='permiso')
    op.create_index(op.f('ix_permiso_codigo'), 'permiso', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('permiso_codigo_key'), 'permiso', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_table('clase')
    op.drop_table('profesor')
    # ### end Alembic commands ###
