"""add token_recuperacion to persona

Revision ID: c676bb98c307
Revises: e47c81f0639c
Create Date: 2026-06-13 19:09:42.987671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c676bb98c307'
down_revision: Union[str, Sequence[str], None] = 'e47c81f0639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_asistencia_reserva'), 'asistencia', type_='unique')
    op.create_index(op.f('ix_asistencia_empleado_registro_id'), 'asistencia', ['empleado_registro_id'], unique=False)
    op.drop_constraint(op.f('asistencia_empleado_registro_id_fkey'), 'asistencia', type_='foreignkey')
    op.drop_constraint(op.f('asistencia_qr_asistencia_id_fkey'), 'asistencia', type_='foreignkey')
    op.drop_constraint(op.f('asistencia_reserva_id_fkey'), 'asistencia', type_='foreignkey')
    op.create_foreign_key(None, 'asistencia', 'reserva', ['reserva_id'], ['reserva_id'])
    op.create_foreign_key(None, 'asistencia', 'empleado', ['empleado_registro_id'], ['persona_id'])
    op.create_foreign_key(None, 'asistencia', 'qr_asistencia', ['qr_asistencia_id'], ['qr_asistencia_id'])
    op.add_column('persona', sa.Column('token_recuperacion', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_qr_asistencia_token_hash'), table_name='qr_asistencia')
    op.create_index(op.f('ix_qr_asistencia_token_hash'), 'qr_asistencia', ['token_hash'], unique=True)
    op.drop_constraint(op.f('qr_asistencia_reserva_id_fkey'), 'qr_asistencia', type_='foreignkey')
    op.create_foreign_key(None, 'qr_asistencia', 'reserva', ['reserva_id'], ['reserva_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_asistencia', type_='foreignkey')
    op.create_foreign_key(op.f('qr_asistencia_reserva_id_fkey'), 'qr_asistencia', 'reserva', ['reserva_id'], ['reserva_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_qr_asistencia_token_hash'), table_name='qr_asistencia')
    op.create_index(op.f('ix_qr_asistencia_token_hash'), 'qr_asistencia', ['token_hash'], unique=False)
    op.drop_column('persona', 'token_recuperacion')
    op.drop_constraint(None, 'asistencia', type_='foreignkey')
    op.drop_constraint(None, 'asistencia', type_='foreignkey')
    op.drop_constraint(None, 'asistencia', type_='foreignkey')
    op.create_foreign_key(op.f('asistencia_reserva_id_fkey'), 'asistencia', 'reserva', ['reserva_id'], ['reserva_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('asistencia_qr_asistencia_id_fkey'), 'asistencia', 'qr_asistencia', ['qr_asistencia_id'], ['qr_asistencia_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('asistencia_empleado_registro_id_fkey'), 'asistencia', 'empleado', ['empleado_registro_id'], ['persona_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_asistencia_empleado_registro_id'), table_name='asistencia')
    op.create_unique_constraint(op.f('uq_asistencia_reserva'), 'asistencia', ['reserva_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
