"""add asistencia and qr_asistencia tables

Revision ID: f3a9b1c2d4e5
Revises: b32b299a9925
Create Date: 2026-05-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a9b1c2d4e5'
down_revision: Union[str, Sequence[str], None] = 'b32b299a9925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'qr_asistencia',
        sa.Column('qr_asistencia_id', sa.Integer(), primary_key=True),
        sa.Column('reserva_id', sa.Integer(), sa.ForeignKey('reserva.reserva_id', ondelete='CASCADE'), nullable=False),
        sa.Column('token_hash', sa.String(length=255), nullable=False),
        sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('expira_en', sa.DateTime(timezone=True), nullable=True),
        sa.Column('escaneado_en', sa.DateTime(timezone=True), nullable=True),
        sa.Column('estado', sa.String(length=50), nullable=False, server_default='activo'),
    )
    op.create_index(op.f('ix_qr_asistencia_reserva_id'), 'qr_asistencia', ['reserva_id'], unique=False)
    op.create_index(op.f('ix_qr_asistencia_token_hash'), 'qr_asistencia', ['token_hash'], unique=False)

    op.create_table(
        'asistencia',
        sa.Column('asistencia_id', sa.Integer(), primary_key=True),
        sa.Column('reserva_id', sa.Integer(), sa.ForeignKey('reserva.reserva_id', ondelete='CASCADE'), nullable=False),
        sa.Column('qr_asistencia_id', sa.Integer(), sa.ForeignKey('qr_asistencia.qr_asistencia_id', ondelete='SET NULL'), nullable=True),
        sa.Column('empleado_registro_id', sa.Integer(), sa.ForeignKey('empleado.persona_id', ondelete='SET NULL'), nullable=True),
        sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('medio_registro', sa.String(length=50), nullable=False),
        sa.UniqueConstraint('reserva_id', name='uq_asistencia_reserva'),
    )
    op.create_index(op.f('ix_asistencia_reserva_id'), 'asistencia', ['reserva_id'], unique=True)
    op.create_index(op.f('ix_asistencia_qr_asistencia_id'), 'asistencia', ['qr_asistencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencia_qr_asistencia_id'), table_name='asistencia')
    op.drop_index(op.f('ix_asistencia_reserva_id'), table_name='asistencia')
    op.drop_table('asistencia')

    op.drop_index(op.f('ix_qr_asistencia_token_hash'), table_name='qr_asistencia')
    op.drop_index(op.f('ix_qr_asistencia_reserva_id'), table_name='qr_asistencia')
    op.drop_table('qr_asistencia')
    # ### end Alembic commands ###
