export const endpoints = {
  login: '/api/login',
  registrarse: '/api/registrarse',
  users: '/api/usuarios',
  registerEmployee: '/api/usuarios/empleados',
  selectLoginRole: '/api/login/select-role',
  currentSession: '/api/login/session',
  logout: '/api/session/logout',
  profileMe: '/api/perfil/me',
  crearClase: '/api/clase/crear',
  listarClases: '/api/clase/lista',
  obtenerProfesores: '/api/profesor/lista',
  actividades: '/api/actividades',
  reservaEspontanea: '/api/reservas/espontanea',
  reservaEspontaneaListaEspera: '/api/reservas/espontanea/lista-espera',
  reservaEspontaneaPagoRetorno: '/api/reservas/espontanea/pago-retorno',
  misPagos: '/api/pagos/',
}
